FROM nvidia/cuda:10.2-runtime-ubi8 as base

RUN yum -y install python39 python39-pip
RUN  pip3.9 install cython torch

RUN git clone https://github.com/Machine-Learning-for-Medical-Language/cnlp_transformers.git /cnlp-transformers
WORKDIR /cnlp-transformers
RUN --mount=type=cache,target=/root/.cache \
  pip install .

# temporary workaround for transformers/huggingface version issue 
RUN pip3.9 uninstall -y huggingface-hub
RUN pip3.9 install huggingface-hub==0.10.1



WORKDIR /opt/cnlp/
# this copy is to support the preload of train models in the downstream images
COPY .. /opt/cnlp/
ENTRYPOINT ["/bin/bash"]

FROM base as dtr
run /usr/bin/python3.9 -c "import sys;sys.path.append('/home/docker');import model_download; model_download.dtr()"
ENTRYPOINT ["cnlpt_dtr_rest", "-p", "8000"]

FROM base as event
run /usr/bin/python3.9 -c "import sys;sys.path.append('/home/docker');import model_download; model_download.event()"
ENTRYPOINT ["cnlpt_event_rest", "-p", "8000"]

FROM base as negation
run /usr/bin/python3.9 -c "import sys;sys.path.append('/home/docker');import model_download; model_download.negation()"
ENTRYPOINT ["cnlpt_negation_rest", "-p", "8000"]

FROM base as temporal
run /usr/bin/python3.9 -c "import sys;sys.path.append('/home/docker');import model_download; model_download.temporal()"
ENTRYPOINT ["cnlpt_temporal_rest", "-p", "8000"]

FROM base as timex
run /usr/bin/python3.9 -c "import sys;sys.path.append('/home/docker');import model_download; model_download.timex()"
ENTRYPOINT ["cnlpt_timex_rest", "-p", "8000"]
