FROM nvidia/cuda:10.2-runtime-ubi8 as cnlp_transformer

RUN yum -y install python39 python39-pip
RUN  pip3.9 install cython torch
RUN pip3.9 install cnlp-transformers

# temporary workaround for transformers/huggingface version issue 
RUN pip3.9 uninstall -y huggingface-hub
RUN pip3.9 install huggingface-hub==0.10.1

run export PATH=”$PATH:/usr/local/bin/python”

WORKDIR /home

ENTRYPOINT ["cnlpt_negation_rest", "-p", "8000"]
