name: Lint and Format

on:
  push:
    branches:
      - main
      - "dev-v[0-9]*"
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"
  pull_request:
    branches:
      - main
      - "dev-v[0-9]*"
    paths:
      - "src/**"
      - "test/**"
      - "pyproject.toml"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.11.8 # same as in pyproject.toml and pre-commit hooks
          args: check
      - uses: astral-sh/ruff-action@v1
        with:
          version: 0.11.8 # same as in pyproject.toml and pre-commit hooks
          args: format --check
